apiVersion: v1
kind: ConfigMap
metadata:
  name: as-config-grpc
  namespace: trustee-operator-system
data:
  as-config.json: |
    {
        "work_dir": "/opt/confidential-containers/attestation-service",
        "policy_engine": "opa",
        "rvps_config": {
          "type": "GrpcRemote",
          "address": "http://127.0.0.1:50003"
        },
        "attestation_token_broker": {
          "type": "Ear",
          "policy_dir": "/opt/confidential-containers/attestation-service/policies"
        },
        "attestation_token_config": {
          "duration_min": 5
        }
    }
