apiVersion: v1
kind: ConfigMap
metadata:
  name: ita-kbs-config-grpc
  namespace: trustee-operator-system
data:
  kbs-config.json: |
    {
        "insecure_http" : true,
        "sockets": ["0.0.0.0:8080"],
        "auth_public_key": "/etc/auth-secret/kbs.pem",
        "private_key": "/etc/https-key/key.pem",
        "certificate": "/etc/https-cert/cert.pem",
        "attestation_token_config": {
          "attestation_token_type": "Jwk",
          "trusted_certs_paths": ["https://portal.trustauthority.intel.com"]
        },
        "grpc_config" : {
          "as_addr": "http://127.0.0.1:50004"
        },
        "repository_config": {
          "type": "LocalFs",
          "dir_path": "/opt/confidential-containers/kbs/repository"
        },
        "policy_engine_config": {
          "policy_path": "/opt/confidential-containers/opa/policy.rego"
        },
        "intel_trust_authority_config" : {
          "base_url": "https://api.trustauthority.intel.com",
          "api_key": "tBfd5kKX2x9ahbodKV1...",
          "certs_file": "https://portal.trustauthority.intel.com"
        }
    }
