apiVersion: v1
kind: ConfigMap
metadata:
  name: ita-resource-policy
  namespace: trustee-operator-system
data:
  policy.rego: |
    package policy

    default allow = false
    allow {
        input["attester_type"] != "sample"
    }
