apiVersion: v1
kind: ConfigMap
metadata:
  name: rvps-config-grpc
  namespace: trustee-operator-system
data:
  rvps-config.json: |
    {
      "storage" : {
        "type": "LocalJson",
        "file_path": "/opt/confidential-containers/rvps/reference-values/reference-values.json"
      }
    }
