apiVersion: v1
kind: ConfigMap
metadata:
  name: rvps-reference-values
  namespace: trustee-operator-system
data:
  reference-values.json: |
    [
      {
        "name": "svn",
        "expiration": "2026-01-01T00:00:00Z",
        "value" : 1
      }
    ]
