//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttestationTokenVerificationSpec) DeepCopyInto(out *AttestationTokenVerificationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttestationTokenVerificationSpec.
func (in *AttestationTokenVerificationSpec) DeepCopy() *AttestationTokenVerificationSpec {
	if in == nil {
		return nil
	}
	out := new(AttestationTokenVerificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpsSpec) DeepCopyInto(out *HttpsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpsSpec.
func (in *HttpsSpec) DeepCopy() *HttpsSpec {
	if in == nil {
		return nil
	}
	out := new(HttpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IbmSEConfigSpec) DeepCopyInto(out *IbmSEConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IbmSEConfigSpec.
func (in *IbmSEConfigSpec) DeepCopy() *IbmSEConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IbmSEConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbsConfig) DeepCopyInto(out *KbsConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbsConfig.
func (in *KbsConfig) DeepCopy() *KbsConfig {
	if in == nil {
		return nil
	}
	out := new(KbsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KbsConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbsConfigList) DeepCopyInto(out *KbsConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KbsConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbsConfigList.
func (in *KbsConfigList) DeepCopy() *KbsConfigList {
	if in == nil {
		return nil
	}
	out := new(KbsConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KbsConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbsConfigSpec) DeepCopyInto(out *KbsConfigSpec) {
	*out = *in
	if in.KbsSecretResources != nil {
		in, out := &in.KbsSecretResources, &out.KbsSecretResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TdxConfigSpec = in.TdxConfigSpec
	out.IbmSEConfigSpec = in.IbmSEConfigSpec
	if in.KbsEnvVars != nil {
		in, out := &in.KbsEnvVars, &out.KbsEnvVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.KbsLocalCertCacheSpec.DeepCopyInto(&out.KbsLocalCertCacheSpec)
	in.KbsDeploymentSpec.DeepCopyInto(&out.KbsDeploymentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbsConfigSpec.
func (in *KbsConfigSpec) DeepCopy() *KbsConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KbsConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbsConfigStatus) DeepCopyInto(out *KbsConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbsConfigStatus.
func (in *KbsConfigStatus) DeepCopy() *KbsConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KbsConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbsDeploymentSpec) DeepCopyInto(out *KbsDeploymentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbsDeploymentSpec.
func (in *KbsDeploymentSpec) DeepCopy() *KbsDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(KbsDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbsLocalCertCacheEntry) DeepCopyInto(out *KbsLocalCertCacheEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbsLocalCertCacheEntry.
func (in *KbsLocalCertCacheEntry) DeepCopy() *KbsLocalCertCacheEntry {
	if in == nil {
		return nil
	}
	out := new(KbsLocalCertCacheEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KbsLocalCertCacheSpec) DeepCopyInto(out *KbsLocalCertCacheSpec) {
	*out = *in
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]KbsLocalCertCacheEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KbsLocalCertCacheSpec.
func (in *KbsLocalCertCacheSpec) DeepCopy() *KbsLocalCertCacheSpec {
	if in == nil {
		return nil
	}
	out := new(KbsLocalCertCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TdxConfigSpec) DeepCopyInto(out *TdxConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TdxConfigSpec.
func (in *TdxConfigSpec) DeepCopy() *TdxConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TdxConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrusteeConfig) DeepCopyInto(out *TrusteeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrusteeConfig.
func (in *TrusteeConfig) DeepCopy() *TrusteeConfig {
	if in == nil {
		return nil
	}
	out := new(TrusteeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrusteeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrusteeConfigList) DeepCopyInto(out *TrusteeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrusteeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrusteeConfigList.
func (in *TrusteeConfigList) DeepCopy() *TrusteeConfigList {
	if in == nil {
		return nil
	}
	out := new(TrusteeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrusteeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrusteeConfigSpec) DeepCopyInto(out *TrusteeConfigSpec) {
	*out = *in
	out.HttpsSpec = in.HttpsSpec
	out.AttestationTokenVerificationSpec = in.AttestationTokenVerificationSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrusteeConfigSpec.
func (in *TrusteeConfigSpec) DeepCopy() *TrusteeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TrusteeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrusteeConfigStatus) DeepCopyInto(out *TrusteeConfigStatus) {
	*out = *in
	if in.KbsConfigRef != nil {
		in, out := &in.KbsConfigRef, &out.KbsConfigRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrusteeConfigStatus.
func (in *TrusteeConfigStatus) DeepCopy() *TrusteeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TrusteeConfigStatus)
	in.DeepCopyInto(out)
	return out
}
