apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: trustee-operator-system
data:
  policy.rego: |
    package policy
    default allow = false
    allow {
      input["submods"]["cpu"]["ear.status"] != "contraindicated"
    }
