# trustee-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trustee-operator
  namespace: trustee-operator-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: trustee-operator
  source: trustee-upstream-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: trustee-operator.v0.1.0
