apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/trustee-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "pull_request" &&
      target_branch == "main" &&
      files.all.exists(path, !path.matches('bundle*|tests/*|.tekton/*bundle*'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: trustee
    appstudio.openshift.io/component: trustee-operator
    pipelines.appstudio.openshift.io/type: build
  name: trustee-operator-on-pull-request
  namespace: ose-osc-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/trustee/trustee-operator:on-pr-{{revision}}
  - name: revision
    value: '{{revision}}'
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: '{"type": "gomod", "path": "."}'
  - name: hermetic
    value: "true"
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/s390x
  pipelineRef:
    resolver: bundles
    params:
    - name: name
      value: docker-build-multi-platform-oci-ta
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta:devel@sha256:73c6701427023daf5791c3e5179ec5b4005a9e7e81fd3f6a6c3d7859d7cbdf42
    - name: kind
      value: pipeline
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  timeouts:
    pipeline: "2h"
status: {}
