[http_server]
sockets = ["0.0.0.0:8080"]
insecure_http = false
private_key = "/etc/https-key/privateKey"
certificate = "/etc/https-cert/certificate"
worker_count = 4

[admin]
type = "DenyAll"
insecure_api = false

[[admin.personas]]
id = "admin"
public_key_path = "/etc/auth-secret/publicKey"

[attestation_token]
insecure_key = false
attestation_token_type = "CoCo"
trusted_certs_paths = ["/etc/attestation-cert/token.crt"]

[attestation_service]
type = "coco_as_builtin"

[attestation_service.attestation_token_config]
duration_min = 5

[attestation_service.rvps_config]
type = "BuiltIn"
storage_type = "LocalJson"

[storage_backend]
storage_type = "LocalFs"

[storage_backend.backends.local_fs]
dir_path = "/opt/confidential-containers/storage"

[storage_backend.backends.local_json]
dir_path = "/opt/confidential-containers/storage/local_json"

[attestation_service.verifier_config.snp_verifier]
# Configure VCEK sources to try, in order. Defaults to [KDS].
vcek_sources = [
    { type = "OfflineStore" },
    { type = "KDS" }
]

[attestation_service.attestation_token_broker.signer]
key_path = "/etc/attestation-key/token.key"
cert_path = "/etc/attestation-cert/token.crt"

[[plugins]]
name = "resource"
storage_backend_type = "kvstorage"
