name: golangci-lint
on:
  pull_request:
    branches:
      - main
      # Skip CI when changes are made to *.md files
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 300s
